### ISSUE TITLE
Doesn't handle whitespace with /W switch

### ISSUE THREAD

**Issue by pedasmith** [jonroig/finger.farm#2]
The /W switch is supposed to be encoded with whitespace -- for example "/W person". However, in fingerserver.js, the ClearUserName will simply remove the /W without clearing the initial whitespace. The user then cannot be found in the database.

It might be best to .trim the userstring while cleaning it:

> var cleanUsername = (string) => {
>     return string
>         .replace('/W', '')
>         .replace('\r\n', '')
>         .**trim()**
>         .toLowerCase();
> };

**Comment by jonroig** [comment]
Done! Again... thx for the feedback!

**Comment by pedasmith** [comment]
You're welcome! My little side project turned into a study of every single piece of FINGER code on Github (and a few others). The number of people who don't handle /W is pretty much everyone :-)
Peter 
    On Monday, February 15, 2021, 08:11:59 PM PST, Jon Roig <notifications@github.com> wrote:  
 
 


Closed #2.
