### ISSUE TITLE
username should be cleaned before being checked for \r\n

### ISSUE THREAD

**Issue by pedasmith** [jonroig/finger.farm#3]
The server doesn't correctly handle the case of a simple /W<CR><LF> command. It's supposed to be just like a regular <CR><LF> command and return all users, but with "more" information. 

However, because you compare username to \r\n in line 48 but only strip the username of the \W in line 64, attemping to do a /W<CR><LF> will fail when it shouldn't

One solution is to move line 64 (const clearName = cleanUsername(username);) up to before line 48, and then use the cleanName compared to blank at line 48. 

> const cleanName = cleanUsername(username);
> if (cleanName === '') {

I haven't tried it, but this should make the /W switch work more reliably.

Thanks for the cool project!

**Comment by jonroig** [comment]
Thanks for the feedback! I think that makes sense... will update in a sec.

**Comment by pedasmith** [comment]
Works like a charm! Thanks!
