### ISSUE TITLE
finger.farm website needs some clarification

### ISSUE THREAD

**Issue by abear1538** [jonroig/finger.farm#4]
On the website it states that the code is "100% free" but it doesn't state what type of free. It should state whether it's free as in free software or free as in beer. Choosing one of the available from the plethora of open source licenses would help.

**Comment by jonroig** [comment]
https://github.com/jonroig/finger.farm/blob/main/LICENSE

**Comment by abear1538** [comment]
Right. Now. Take that information and put it on your website.
